import Head from "next/head";
import Navbar from "./Navbar";

export default function Layout({ children, title }) {
  return (
    <div className="layout">
      <Head>
        <title>{title || "Next App"}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      {children}
    </div>
  );
}
